# cargo make build
[tasks.build]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-dir", "pkg"]

[tasks.build-node]
command = "wasm-pack"
args = ["build", "--target", "nodejs", "--out-dir", "node"]

[tasks.test-wasm]
command = "wasm-pack"
args = ["test", "--node"]

[tasks.test-cargo]
command = "cargo"
args = ["test"]

[tasks.test]
clear = true
dependencies = ["test-cargo", "test-wasm"]
